;;; Sierra Script
;;; Verbs.sh -- Produced by SCI Companion
;;; This file should only be edited with the SCI Companion message editor

;;; VERBS

(define V_WALK 3)
(define V_LOOK 1)
(define V_TALK 2)
(define V_COMMAND 24)
(define V_DO 4)
(define V_HELP 5)
(define V_USEIT 7)
(define V_SPIKE 31)
(define V_ANTACID 29)
(define V_OXYGEN_TANK 25)
(define V_CLOAK 12)
(define V_CLOAK_ORD 11)
(define V_DAMAGE_ORD 10)
(define V_GAME 8)
(define V_FORGET_ORD 15)
(define V_FROC 23)
(define V_GREET 13)
(define V_KEY 16)
(define V_KIZ_BRANCH 21)
(define V_KIZ_FRUIT 22)
(define V_LOWER_ORD 9)
(define V_RAISE_ORD 14)
(define V_SAFETY_CONES 20)
(define V_SCRUBBER 18)
(define V_BUCKAZOIDS 17)
(define V_DIST_CAP 19)
(define V_FUSE 28)
(define V_SHIP_OPENER 6)
(define V_TORCH 30)
(define V_COMMUNICATOR 32)
(define V_HOLE_PUNCH 33)
(define V_CLOAKING_DEVICE 26)
(define V_SPACE_MONKEYS 34)
(define V_PAPER 42)
(define V_REBREATHER 39)
(define V_WD40_HEAD 38)
(define V_BUSINES_CARD 35)
(define V_GENETIX_CAN 36)
(define V_NITRO_TANK 37)

