;;; Sierra Script
;;; Talkers.sh -- Produced by SCI Companion
;;; This file should only be edited with the SCI Companion message editor

;;; 

(define NARRATOR 99)
(define PRINTMSG 97)
(define BABA 22)
(define IGOR 1)
(define GNOME 13)
(define AVIS 5)
(define OLGA 11)
(define BELLA 16)
(define INNKEEPER 12)
(define TANYA 4)
(define TANYA_VAMPIRE 39)
(define TOBY 3)
(define TOBY_NICE 40)
(define PIOTYR 2)
(define ERANA 33)
(define BURGOMEISTER 7)
(define GYPSY 8)
(define ERASMUS 48)
(define FENRUS 49)
(define GATEKEEPER 23)
(define DOMOVOI 17)
(define SYSMSG 98)
(define BONEHEAD 24)
(define CRANIUM 18)
(define ANNA 20)
(define HANS 9)
(define FRANZ 15)
(define IVAN 14)
(define KATRINA 6)
(define KATRINA_HOOD 35)
(define KATRINA_RED 36)
(define KATRINA_BLACK 37)
(define LESHY 19)
(define NIKOLAI 10)
(define GOON1 26)
(define GOON2 27)
(define RUSALKA_YOUNG 28)
(define RUSALKA_OLD 38)
(define QUEEN 30)
(define CHIEF 29)
(define DAVY 21)
(define NIKOLAI_GHOST 31)
(define MAGDA 32)

