;;; Sierra Script
;;; Verbs.sh -- Produced by SCI Companion
;;; This file should only be edited with the SCI Companion message editor

;;; VERBS

(define V_DIE 100)
(define V_HELP 9)
(define V_TALK 2)
(define V_LOOK 1)
(define V_TRIGGER 82)
(define V_OPEN 80)
(define V_FETCH 87)
(define V_FORCEBOLT 88)
(define V_LEVITATE 89)
(define V_SLEEP 104)
(define V_DOIT 6)
(define V_HEAL 102)
(define V_DO 4)
(define V_FLAME 86)
(define V_LIGHTNING 93)
(define V_FROSTBITE 79)
(define V_DAZZLE 83)
(define V_CALM 85)
(define V_STAFF 92)
(define V_RITUAL 94)
(define V_REVERSAL 90)
(define V_JUGGLE 91)
(define V_DAGGER 37)
(define V_ROCK 21)
(define V_GRAPNEL 33)
(define V_JUMP 10)
(define V_WALK 3)
(define V_DETECT 81)
(define V_PURSE 15)
(define V_KNOB 78)
(define V_CANDY 23)
(define V_FLOWERS 59)
(define V_ACTIONS 7)
(define V_CONTROLS 8)
(define V_REST 103)
(define V_HEAL_POTION 18)
(define V_MANA_FRUIT 16)
(define V_CURE_POTION 17)
(define V_RATIONS 19)
(define V_CLOTH 54)

