;;; Sierra Script 1.0 - (do not remove this comment)
;
; * SCI Game Header
; *************************************************************************
; * Put all the defines specific to your game in here

(include system.sh) (include sci2.sh)

(define LASTCEL			255)
(define GLORY_WINDOW	559)

;View defines
(define vEgo				0)
(define vEgoStanding		4)
(define vEgoRunning			5)
(define vGhosts				17)
(define vBabaSkulls			23)
(define vGraveyardStuff		63)
(define vEgoSwingSword		109)
(define vEgoStabSword		110)
(define vEgoParry			111)
(define vEgoDodgeRightSword	112)
(define vEgoHitSword		113)
(define vZara				315)
(define vDartBoard			341)
(define vBear				420)
(define vSaurus				430)
(define vCheetaur			440)
(define vMoreCheetaur		442)
(define vDragon				460)
(define vMoreDragon			462)
(define vSelEgo				505)
(define vCharSel			506)
(define vSelFighter			526)
(define vSelWizard			527)
(define vSelThief			528)
(define vOtto				606)
(define vSpeed				799)
(define vIcons				800)
(define vStatusBar			803)
(define vIntroFlame			906)
(define vIntroFlame2		907)
(define vQFGCooldown		908)
(define vHeroCooldown		909)
(define vIntroDragon		910)
(define vIntroTitle			912)
(define vHalfSparkle		988)
(define vWindowBorders		989)
(define vControlPanel		995)
(define vZaraBust			1314)

;Picture and room defines
(define pHalfDome		1)
(define rEranasPeace	10)
(define rDemoGraveyard	11)
(define rBearCave		14)
(define rKoboldCave		15)
(define rBabaHutOutside	22)
(define rGraveyard		64)
(define rHalfDome		100)
(define rBigEgo			148)
(define rTownOutlook	300)
(define rMainStreet		310)
(define rMagicShop		314)
(define rDagNabIt		340)
(define pBlack 			400)
(define pForestArena	460)
(define rGenericForest	700)
(define pIntro			902)
(define pCharSel		905)

;Sound defines
(define sThemeSong		1)
(define sHardBattle		2)
(define sGhosts			12)
(define sCave			20)
(define sBabaHutOutside	23)
(define sEranasPeace	24)
(define sForest			25)
(define sTeleport		28)
(define sKnifeStick1	29)
(define sKnifeStick2	30)
(define sKnifeThrow		31)
(define sFireDart		33)
(define sHardBattleEnd	38)
(define sThunder		45)
(define sFire			46)
(define sWind			47)
(define sMagicShop		67)
(define sBrigand		73)
(define sTown			93)
(define sEndGame		99)
(define sHalfDome		100)
;demo sounds
(define sTwinkle		992)
(define sSwoosh			993)
(define sMoan1			994)
(define sMoan2			995)
(define sDemoFinale		996)
(define sRoar			997)
(define sShortBattle	998)
(define sShortIntro		999)