;;; Sierra Script 1.0 - (do not remove this comment)
(script# INVDESC)
(include game.sh)
(use Intrface)
(use System)

(public
	rm046 0
)

(instance rm046 of Code
	(method (init)
		(Print INVDESC 0)
		(Print INVDESC 1)
		(Print INVDESC 2)
		(Print INVDESC 3)
		(Print INVDESC 4)
		(Print INVDESC 5)
		(Print INVDESC 6)
		(Print INVDESC 7)
		(Print INVDESC 8)
		(Print INVDESC 9)
		(Print INVDESC 10)
		(Print INVDESC 11)
		(Print INVDESC 12)
		(Print INVDESC 13)
		(Print INVDESC 14)
		(Print INVDESC 15)
		(Print INVDESC 16)
		(Print INVDESC 17)
		(Print INVDESC 18)
		(Print INVDESC 19)
		(Print INVDESC 20)
		(Print INVDESC 21)
		(Print INVDESC 22)
		(Print INVDESC 23)
		(Print INVDESC 24)
		(Print INVDESC 25)
		(Print INVDESC 26)
	)
)
