;;; Sierra Script 1.0 - (do not remove this comment)
;;; ***********************************************
;;; 
;;; Do not edit this file!! created by RMessage.exe 
;;; edit either translation file ..\gtransys\LOGGER.SC (usual case)
;;; or original file ..\system\LOGGER.SC (if you must!)
;;; 
;;; ***********************************************
(script# LOGGER)
(include game.sh)
(use Main)
(use Print)
(use PolyPath)
(use System)

;;;(procedure
;;;	Log
;;;)

(public	sysLogger 0)

(local
	logHandle = 0
)

(enum 1
	Txt
	Num
	Uns
	Hex
	Inp
	Tim
	Dat
)

(define MAXCOMMENTS 10)

(procedure (Log how aLabel anArg &tmp [buffer 40] tm retval)
	(Format @buffer {%15s: } aLabel)
	(FileIO fileFPuts logHandle @buffer)
	(= buffer NULL)
	(switch how
		(Txt	(StrCpy @buffer (if anArg anArg else {})))
		(Num	(Format @buffer {%d} anArg))
		(Uns	(Format @buffer {%u} anArg))
		(Hex	(Format @buffer {%x} anArg))
		(Inp
			(if anArg
				(GetInput @buffer 66 anArg 999)
			)
			(= retval (StrLen @buffer))
		)
		(Tim
			; get system time stamp (minutes after 12:00)
			(= tm (GetTime SYSTIME2))
			(Format 
				@buffer 
				{%02d:%02d:%02d}
				(>> tm 11)
				(& (>> tm 5) %111111)
				(* (& tm %11111) 2)
			)
		)
		(Dat
			; get system date stamp (mm/dd/yy)
			(= tm (GetTime SYSDATE))
			(Format 
				@buffer 
				{%02d/%02d/%02d}
				(& (>> tm 5) %1111)
				(& tm %11111)
				(+ 80 (>> tm 9))
			)
		)
	)
	
	(StrCat @buffer {\r})
	(FileIO fileFPuts logHandle @buffer)
	retval
);procedure Log

(instance sysLogger of Code
	
	(method (doit 
			&tmp	i j l c firstNote theDrv commented saveInfont
			[str 40]
			[cfgPath 30]
			[thePath 30]
			[theToken 30]
			[QAinitials 20]
			[kbdDrvEntry 40]
			[joyDrvEntry 40]
			[videoDrvEntry 40]
			[soundDrvEntry 40]
			[mouseDrvEntry 40]
			[audioDrvEntry 40]
		)

		;;	initialize some variables:
		
		(= saveInfont inputFont)
		(= inputFont 999)
		
		(= str 
			(= thePath 
				(= theToken 
					(= kbdDrvEntry 
						(= joyDrvEntry 
							(= videoDrvEntry
								(= soundDrvEntry 
									(= mouseDrvEntry
										(= audioDrvEntry 0)))))))))
		
		(= firstNote (== 0 (StrLen @sysLogPath)))
		
		;; if path argument is NULL, we need some initial info 
		(if firstNote
			(while (not (< 0 (StrLen @thePath) 19))
				(Print
				 	font:		999,
				 	addText:	{Enter drive letter, path, and your name\n
				 				(no extension, max 40 characters)},
				 	addEdit: @thePath 40 0 20,
				 	init:
				)
			)
			(StrCpy @sysLogPath @thePath 40)
		)

;		; This commented code was intended to check disk space before
;		;	trying to write a log, but the kernel call CheckFreeSpace
;		;	doesn't appear to be working!
;
;		; First thing we do is check available disk space
;		; If we don't have at least 2k, don't even bother
;		;	with the rest of this - BKH
;
;		(if (not (CheckFreeSpace @sysLogPath))
;			(Print
;				font:			999,
;				addText:		{Error: Not enough disk space for new entry},
;				init:
;			)
;			(return FALSE)
;		)

		;;access "memory variable" file to seed data
		(Format @thePath {%s.mem} @sysLogPath)
		
		(if (!= -1 (= logHandle (FileIO fileOpen @thePath fRead)))
			(FileIO fileFGets @QAinitials 80 logHandle)
			(FileIO fileFGets @cfgPath 80 logHandle)
			(FileIO fileClose logHandle)
		else
			(= QAinitials 0)
			(StrCpy @cfgPath {resource.cfg})
		)
		
		(if firstNote
			(Print
				font:		999,
				addText:	{Enter your login name\n
							(max 8 characters):},
				addEdit: @QAinitials 12 0 20,
				init:
			)
			(StrAt @QAinitials 8 NULL)
		)
		
		;; read configuration file
		(while
			(and 
				(or
					(not firstNote)
					(Print
						font:		999,
						addText:	{Enter configuration file name\n
									(or hit return to skip):},
						addEdit:	@cfgPath 30 0 20,
						init:
					)
				)
				(== -1 (= logHandle (FileIO fileOpen @cfgPath fRead)))
				(StrAt @cfgPath 0)
			)
			(StrAt @cfgPath 0 0)
		);while
		
		(if (!= -1 logHandle) ; opened config file
			
			(while (FileIO fileFGets @str 80 logHandle)
				
				; strip leading whitespace
				(for 
					((= i 0)) 
					(and (= c (StrAt @str i)) (OneOf c TAB SPACEBAR)) 
					((++ i))
				);for
				
				(for ((= j 0))
					(and
						(= c (StrAt @str i))
						(not (OneOf c `= `: TAB SPACEBAR))
					) 
					((++ i) (++ j))
					(StrAt @theToken j c)
				)
				
				(StrAt @theToken j NULL)
				
				(= theDrv
					(cond
						((== 0 (StrCmp @theToken {kbdDrv}))		@kbdDrvEntry)
						((== 0 (StrCmp @theToken {joyDrv}))		@joyDrvEntry)
						((== 0 (StrCmp @theToken {videoDrv}))	@videoDrvEntry)
						((== 0 (StrCmp @theToken {soundDrv}))	@soundDrvEntry)
						((== 0 (StrCmp @theToken {mouseDrv}))	@mouseDrvEntry)
						((== 0 (StrCmp @theToken {audioDrv}))	@audioDrvEntry)
					);cond
				);=
				
				(if theDrv
					
					;;skip trailing white space
					(while (and (= c (StrAt @str i)) (OneOf c `= `: TAB SPACEBAR))
						(++ i)
					)
					
					;;find last delimiter and period
					(for ((= j i) (= l 0)) (= c (StrAt @str j)) ((++ j))
						
					(if (OneOf c `: `
					;EO: This commented out part can't be compiled, since it causes SCICompanion to give an error:
					;Error: (Logger.sc) Expected an expression. (224, 36): "\"
                  		;\\
                  		`/)
							(= i (+ j 1))
						)
						(if (== c `.)
							(= l (- j i))
						)
					);for
					
					(if (== l 0)
						(= l (- j i))
					)
					
					(StrCpy theDrv (+ @str i) l)
					
				);if theDrv
				
			);while
			
			(FileIO fileClose logHandle)
			
		);if opened config file
		
		;;NOW, open log file!
		(Format @thePath {%s.log} @sysLogPath)
		(if (and
				firstNote
				(or
					;; file doesn't exist so start new one
					(== -1 (= logHandle (FileIO fileOpen @thePath fRead)))
					;; file exists, ask whether to overwrite
					(and (Format @str {Log file \"%s\" exists} @thePath) FALSE)
					(Print
						font:			999,
						addText:		@str,
						addButton: 	FALSE {Append to it} 0 12,
						addButton: 	TRUE	{Overwrite it} 75 12,
						saveCursor:	TRUE,
						init:
					)
				);or
			);and
			
			(FileIO fileClose logHandle)
			(= logHandle (FileIO fileOpen @thePath fTrunc))
		else
			(= logHandle (FileIO fileOpen @thePath fAppend))
		);if-else
		
		(if (== -1 logHandle)
			(Print
				font:			999,
				addTextF:	{Error: Couldn't open %s} @thePath,
				init:
			)
			
		else
			
			;;ษอออออออออออออออออออออออออออออออออออออป
			;;บ    Match Fields With Import Items   บ
			;;ฬอออออออออออออออออออออออออออออออออออออน
			;;บ Number of Items in Import File: 65  บ
			;;ฬออออออหออออออออออออออหออออออหออออออออน
			;;บ Item บ Field Name   บ Type บ Length บ
			;;ฬออออออฮออออออออออออออฮออออออฮออออออออน
			;;บ   1  บ BUG-NUMBER   บ   N  บ     7  บ
			;;บ   2  บ BACKWARD     บ   B  บ     7  บ
			;;บ   3  บ FORWARD      บ   F  บ     7  บ
			;;บ   4  บ GAME         บ   A  บ     6  บ
			
			(Log Txt {GAME} (theGame name?))
			
			;;บ   5  บ VERSION      บ   A  บ     7  บ
			
			(Log Txt {VERSION} version)
			
			;;บ   6  บ QA-DATE      บ   D  บ     6  บ
			
			(Log Dat {QA-DATE})
			
			;;บ   7  บ ANALYST      บ   A  บ     3  บ
			
			(Log Txt {ANALYST} @QAinitials)
			
			;;บ   8  บ QA-STATUS    บ   A  บ     1  บ
			;;บ   9  บ RE-CHECK     บ   D  บ     6  บ
			;;บ  10  บ SEVERITY     บ   A  บ     8  บ
			
			(Log Txt {SEVERITY}
				(Print
 					font:			999,
					addText:		{Severity of bug...},
					addButton: 	{Fatal} 		{FATAL} 		0 12,
					addButton: 	{Moderate} 	{MODERATE} 	40 12,
					addButton: 	{Minor} 		{MINOR} 		100 12,
					saveCursor:	TRUE,
					init:
				)
			)
			
			;;บ  11  บ REPRODUCIBLE บ   A  บ     3  บ

			(Log Txt {REPRODUCIBLE}
				(Print
					font:			999,
					addText:		{Reproducible?},
					addButton:	{Yes} {YES}	0 12,
					addButton:	{No} 	{NO}	40 12,
					addButton:	{Intermittent} {INTERMITTENT} 80 12,
					saveCursor:	TRUE,
					init:
				)
			)

			;;บ  12  บ QA-COMMENT1  บ   A  บ    76  บ
			;;บ  13  บ QA-COMMENT2  บ   A  บ    76  บ
			;;บ  14  บ QA-COMMENT3  บ   A  บ    76  บ
			;;บ  15  บ QA-COMMENT4  บ   A  บ    76  บ
			;;บ  16  บ QA-COMMENT5  บ   A  บ    76  บ
			;;บ  17  บ QA-COMMENT6  บ   A  บ    76  บ
			;;บ  18  บ QA-COMMENT7  บ   A  บ    76  บ
			;;บ  19  บ QA-COMMENT8  บ   A  บ    76  บ
			;;บ  20  บ QA-COMMENT9  บ   A  บ    76  บ
			;;บ  21  บ QA-COMMENT10 บ   A  บ    76  บ
			
			(for 
				((= i 1) (= commented TRUE)) 
				(<= i MAXCOMMENTS)
				((++ i)) 
				
				(Format @theToken {QA-COMMENT%d} i)
				(Format @str {Comment line %d of %d:} i MAXCOMMENTS)
				(if commented
					(= commented (Log Inp @theToken @str))
				else
					(Log Txt @theToken NULL)
				)
			)
			;;บ  22  บ DEPARTMENT   บ   A  บ    11  บ
			
			(Log Txt {DEPARTMENT}
				(Print
					font:			999,
					addText:		{Who can fix bug...},
					addButton: 	{Art} 			{ART}   		0 12,
					addButton: 	{Programming} 	{PROG}  		40 12,
					addButton:	{Music} 			{MUSIC} 		80 12,
					addButton: 	{Design} 		{DESIGN}	 	120 12,
					saveCursor:	TRUE,
					init:
				)
			)
			
			;;บ  23  บ RESPONSE-BY  บ   A  บ     3  บ
			;;บ  24  บ RESP-DATE    บ   D  บ     6  บ
			;;บ  25  บ ACTION       บ   A  บ     1  บ
			;;บ  26  บ RESPONSE-1   บ   A  บ    76  บ
			;;บ  27  บ RESPONSE-2   บ   A  บ    76  บ
			;;บ  28  บ RESPONSE-3   บ   A  บ    76  บ
			;;บ  29  บ RESPONSE-4   บ   A  บ    76  บ
			;;บ  30  บ RESPONSE-5   บ   A  บ    76  บ
			
			;;บ  31  บ ROOM         บ   N  บ     4  บ
			
			(Format @str {%04d} curRoomNum)
			(Log Txt {ROOM} @str)
			
			;;บ  32  บ ROOM-SCRIPT  บ   A  บ    15  บ
			;;บ  33  บ ROOM-STATE   บ   N  บ     5  บ
			
			(= i (curRoom script?))
			(Log Txt {ROOM-SCRIPT} (if i (i name?)))
			(Log Num {ROOM-STATE} (if i (i state?)))
			
			;;บ  34  บ EGO-X        บ   A  บ     3  บ
			;;บ  35  บ EGO-Y        บ   A  บ     3  บ
			;;บ  36  บ EGO-Z        บ   A  บ     3  บ
			
			(Log Num {EGO-X} (ego x?))
			(Log Num {EGO-Y} (ego y?))
			(Log Num {EGO-Z} (ego z?))
			
			;;บ  37  บ EGO-SCRIPT   บ   A  บ    15  บ
			;;บ  38  บ EGO-STATE    บ   N  บ     5  บ
			
			(= i (ego script?))
			(Log Txt {EGO-SCRIPT} (if i (i name?)))
			(Log Num {EGO-STATE} (if i (i state?)))
			
			;;บ  39  บ EGO-VIEW     บ   A  บ     4  บ
			;;บ  40  บ EGO-LOOP     บ   A  บ     2  บ
			;;บ  41  บ EGO-CEL      บ   A  บ     2  บ
			;;บ  42  บ EGO-PRIORITY บ   A  บ     3  บ
			;;บ  43  บ EGO-HEADING  บ   A  บ     3  บ
			
			(Log Num {EGO-VIEW} (ego view?))
			(Log Num {EGO-LOOP} (ego loop?))
			(Log Num {EGO-CEL} (ego cel?))
			(Log Num {EGO-PRIORITY} (ego priority?))
			(Log Num {EGO-HEADING} (ego heading?))
			
			;;บ  44  บ EGO-CYCLER   บ   A  บ    15  บ
			
			(Log Txt {CYCLER} (if (ego cycler?) ((ego cycler?) name?)))
			
			;;บ  45  บ EGO-MOVER    บ   A  บ    15  บ
			;;บ  46  บ MOVER-X      บ   A  บ     3  บ
			;;บ  47  บ MOVER-Y      บ   A  บ     3  บ
			;;บ  48  บ EGO-MOVESPD  บ   A  บ     4  บ
			
			(= i (ego mover?))
			(Log Txt {EGO-MOVER} (if i (i name?)))
			(Log Num {MOVER-X} 
				(cond 
					((not i) NULL)
					((i isMemberOf: PolyPath) (i finalX?))
					(else (i x?))
				)
			)
			(Log Num {MOVER-Y} 
				(cond 
					((not i) NULL)
					((i isMemberOf: PolyPath) (i finalY?))
					(else (i y?))
				)
			)
			
			(Log Num {EGO-MOVESPD} (ego moveSpeed?))
			
			;;บ  49  บ SIGNAL-BITS  บ   A  บ     4  บ
			
			(Log Hex {SIGNAL-BITS} (ego signal?))
			
			;;บ  50  บ ILLEGAL-BITS บ   A  บ     4  บ
			
			(Log Hex {ILLEGAL-BITS} (ego illegalBits?))
			
			;;บ  51  บ HOWFAST      บ   A  บ     1  บ
			
			(Log Num {HOWFAST} howFast)
			
			;;บ  52  บ ICONBAR      บ   A  บ    15  บ
			
			(Log Txt {ICONBAR} (if theIconBar (theIconBar name?)))
			(Log Txt {CUR-ICON} 
				(if (and theIconBar (theIconBar curIcon?))
					((theIconBar curIcon?) name?)
				)
			)
			;;บ  53  บ DETAIL-LEVEL บ   A  บ     2  บ
			
			(Log Num {DETAIL-LEVEL} (theGame detailLevel:))
			
			;;บ  54  บ CD-AUDIO     บ   A  บ     1  บ
			
			(Log Num {CD-AUDIO} (& msgType CD_MSG))
			
			;;บ  55  บ VIDEO-DRV    บ   A  บ     8  บ
			;;บ  56  บ SOUND-DRV    บ   A  บ     8  บ
			;;บ  57  บ AUDIO-DRV    บ   A  บ     8  บ
			;;บ  58  บ KEYBOARD-DRV บ   A  บ     8  บ
			;;บ  59  บ JOY-DRV      บ   A  บ     8  บ
			;;บ  60  บ MOUSE        บ   A  บ     1  บ
			
			(Log Txt {VIDEO-DRV} @videoDrvEntry)
			(Log Txt {SOUND-DRV} @soundDrvEntry)
			(Log Txt {AUDIO-DRV} @audioDrvEntry)
			(Log Txt {KEYBOARD-DRV} @kbdDrvEntry)
			(Log Txt {JOY-DRV} @joyDrvEntry)
			(Log Txt {MOUSE} @mouseDrvEntry)
			
			
			;;บ  61  บ LARGEST-HEAP บ   A  บ     5  บ
			;;บ  62  บ FREE-HEAP    บ   A  บ     5  บ
			;;บ  63  บ TOTAL-HUNK   บ   A  บ     3  บ
			;;บ  64  บ LARGEST-HUNK บ   A  บ     5  บ
			;;บ  65  บ FREE-HUNK    บ   A  บ     3  บ
			
			(Log Uns {LARGEST-HEAP} (MemoryInfo LargestPtr))
			(Log Uns {FREE-HEAP} (MemoryInfo FreeHeap))
			(Log Uns {TOTAL-HUNK} (>> (MemoryInfo TotalHunk) 6))
			(Log Uns {LARGEST-HUNK} (MemoryInfo LargestHandle))
			(Log Uns {FREE-HUNK} (>> (MemoryInfo FreeHunk) 6))
			
			;;ศออออออสออออออออออออออสออออออสออออออออผ
			
			(FileIO fileFPuts logHandle {**********************************\r})
			(FileIO fileClose logHandle)
		);if opened log file
		
		(Format @thePath {%s.mem} @sysLogPath)
		(if (and
				(== -1 (= logHandle (FileIO fileOpen @thePath fTrunc))) ;existing file
				(== -1 (= logHandle (FileIO fileOpen @thePath fAppend))) ;new file
			)
			(Print
				font:			999,
				addTextF:	{Error: Couldn't open memory file %s!} @thePath,
				init:
			)
		else
			(FileIO fileFPuts logHandle @QAinitials)
			(FileIO fileFPuts logHandle {\n})
			(FileIO fileFPuts logHandle @cfgPath)
			(FileIO fileFPuts logHandle {\n})
			(FileIO fileClose logHandle)
		)
		
		(= inputFont saveInfont)
		
		;; unload me
		(DisposeScript LOGGER)
	)
)
