;;; Sierra Script
;;; Talkers.sh -- Produced by SCI Companion
;;; This file should only be edited with the SCI Companion message editor

;;; 

(define NARRATOR 99)
(define SYSMSG 97)
(define LAURA 2)
(define DAD 1)
(define TUTSMITH 9)
(define SAM 3)
(define LOFAT 4)
(define SARGEANT 5)
(define ZIGGY 6)
(define CRODFOLLER 7)
(define FLAPPER 8)
(define PIPPIN 10)
(define WATNEY 11)
(define STEVE 12)
(define ROCCO 13)
(define BOB 14)
(define IRMGAARD 15)
(define BUM 16)
(define BOUNCER 17)
(define HEIMLICH 18)
(define ORILEY 19)
(define BEAR 20)
(define CORONER 21)
(define BARTENDER 22)
(define ERNIE 23)
(define LUIGI 24)
(define OLYMPIA 25)
(define PULLITZER 26)
(define RAMESES 27)
(define YVETTE 28)
(define COUNTESS 29)
(define PIANO_PLAYER 30)
(define SINGER 31)
(define STINKY 32)
(define BIFF 33)
(define TUBBY 34)
(define DRUNK 41)
(define MAN3 37)
(define MAN1 35)
(define MAN2 36)
(define REX 39)
(define WANDERER 38)

