;;; Sierra Script
;;; Verbs.sh -- Produced by SCI Companion
;;; This file should only be edited with the SCI Companion message editor

;;; VERBS

(define V_LOOK 1)
(define V_TALK 2)
(define V_DIE 45)
(define V_SKELETON_KEY 18)
(define V_WALK 3)
(define V_DO 4)
(define V_PRAGFAIL 47)
(define V_ASK 6)
(define V_CLAIM_TICKET 5)
(define V_BASEBALL 7)
(define V_MAGNIFIER 8)
(define V_WATERGLASS 38)
(define V_HELP 12)
(define V_EXIT 13)
(define V_TITLE 48)
(define V_MUMMY 9)
(define V_COUPON 10)
(define V_BIFOCALS 36)
(define V_CARBON_PAPER 39)
(define V_CHARCOAL 43)
(define V_WIRE 44)
(define V_GOWN 42)
(define V_SHOE 40)
(define V_CHEESE 27)
(define V_GARTER 28)
(define V_DAGGER 22)
(define V_DESK_KEY 16)
(define V_SNAKE_OIL 25)
(define V_LANTERN 26)
(define V_NOTEBOOK 14)
(define V_SANDWICH 15)
(define V_PRESS_PASS 11)
(define V_POCKET_WATCH 17)
(define V_MEAT 19)
(define V_WIRECUTTERS 21)
(define V_BONE 29)
(define V_GRAPES 41)
(define V_LIGHTBULB 33)
(define V_ANKH 31)
(define V_BOOT 23)
(define V_SALTS 24)
(define V_LASSO 30)
(define V_PIPPIN_PAD 32)
(define V_WATNEY_FILE 34)
(define V_WARTHOG_HAIR 35)
(define V_RED_HAIR 37)

