;;; Sierra Script
;;; Verbs.sh -- Produced by SCI Companion
;;; This file should only be edited with the SCI Companion message editor

;;; VERBS

(define V_LOOK 6)
(define V_DO 7)
(define V_WALK 3)
(define V_HELP 83)
(define V_TALK 85)
(define V_NOSE 86)
(define V_EXIT 128)
(define V_PAW 30)
(define V_TEETH 89)
(define V_TRIVIA 84)
(define V_GAME 98)
(define V_BONBONS 75)
(define V_BEN_KEY 124)
(define V_BACKSCRATCHER 60)
(define V_BEN_PACKAGE 36)
(define V_ELECBOOK 37)
(define V_OPENBOOK 38)
(define V_CARPETBAG_CLOSED 68)
(define V_CARPETBAG_OPEN 69)
(define V_CHOCOLATE 74)
(define V_IMA_COSTUME 122)
(define V_DOG_HARNESS 17)
(define V_IMA_DRESS_FAN 147)
(define V_IMA_DRESS 114)
(define V_IMA_DRESS_HEAD 148)
(define V_IMA_FAN 18)
(define V_IMA_FAN_HEAD 149)
(define V_FLEAS 34)
(define V_IMA_KEY 32)
(define V_CABBAGE 52)
(define V_LEYDEN_JAR_CHARGED 55)
(define V_EMPTY_JAR 49)
(define V_TIN 50)
(define V_LEYDEN_JAR_FINISHED 54)
(define V_LEYDEN_JAR_UNFINISHED 125)
(define V_HERB_CLUSTER 23)
(define V_HERB_PACKET 24)
(define V_PEBBLES 96)
(define V_PRAGFAIL_PEP 88)
(define V_PRAGFAIL_DOG 90)

