;;; Sierra Script 1.0 - (do not remove this comment)
;Hero's Quest Framework scripts
(define MAIN			0)
(define HQINIT			1)
(define NOTICE			2)
(define INVDESC			3)	;text only
(define DRINK 			5)
(define EAT 			6)
(define SLEEP 			7)
(define REST			8)
(define NOTICE2			9)

(define SLEEPALLNIGHT	88)		;EO: This has number 88, which was previously a room removed from this version.
(define CASTDART		100)
(define THROWKNIFE		101)
(define THROWROCK		102)
(define GETROCK			103)
(define CASTCALM		104)
(define CASTOPEN		105)
(define CASTDAZZ		106)
(define EGOSEZ			120)	;doVerb on ego
(define PRAGFAIL		121)	;pragmaFail on ego
(define PAINREACTION	155)
(define INTRO			200)
(define CHARSEL			202)
(define CHALLOC			203)
(define CHARSHEET		204)
(define STATUSBAR		205)
(define GLORYINV		206)
(define MAZEBUG			238)
(define SPEED			299)
(define TIMECYC			419)
(define MANTRAY_ACTIONS	436)
(define TELLER			550)
(define WARE			551)
(define ABOUT			556)
(define ACTIONBAR		557)
(define SPELLS			558)
(define GLORY_WINDOW	559)
(define ENDGAME			600)
(define CHARSAVE 		601)
(define ENDGAME2		602)
(define LOGOROOM		603)
(define DOOR 			800)
(define TALKOBJ			803)
(define KEYCURSOR		810)
(define	TARGET			812)
(define TIME			813)
(define PROCS			814)
(define GLORY_PRINT		815)
(define GLORY_OBSTACLES 816)
(define STARTAROOM		896)

; Locales and Regions
(define DEBUG	 298) ;Locale
(define TOWN 	 801) ;Locale
(define FOREST 	 804) ;Locale
(define GHOSTS 	 805) ;Actors and Scripts for CEMETERY
(define CEMETERY 806) ;Region
(define CASTLE 	 807) ;Locale
(define STREET 	 811) ;Locale

;Picture and room defines
; (includes room-specific views)
(define pHalfDome			1)
(define rEranasPeace		10)
(define rDemoGraveyard		11)
(define rBearCave			14)
(define rKoboldCave			15)
(define rBabaHutOutside		22)
(define vBabaSkulls			23)
(define rWizardGame			32)
(define rCastleCourtyard	39)
(define rCastleDoors		41)
(define rGoblinHideout		45)
(define vGraveyardStuff		63)
(define rGraveyard			64)
(define rTownOutside		65)
(define rFaeryRing			70)
(define vEgoDance			71)
(define vEgoGetDust			72)
(define rTargetRange		73)
(define rTrollDen			88)
(define rSecretPassage		89)
(define rBrigandAmbush		91)

(define pValleyWideShot		101)
(define vEndGameDevs		138)
(define vEndGameCast		139)
(define rCastleAnteroom		141)
(define pBigEgo				148)
(define rFaeryRingNight		170)

;Town area
(define rTownEntryway	300)
(define rMainStreet		310)
(define rGuildHall		311)
(define rMagicShop		314)
(define vZara			315)
(define rMarketStreet	320)
(define rTownShop		322)
(define rTavernStreet	330)
(define rAlley			333)
(define rAlleyNight		334)
(define rDagNabIt		340)

(define pBlack 			400)
(define pWhite			401)
(define pLeaderToElsa	402)
(define pBearToBarnard	425)
(define pForestArena	430)
(define pTrollCaveArena	465)
(define pGenericForest	700)

(define pBlueSkyForCarpet 750)

;Ego views
(define vEgo	0)
(define vEgoSlip	3)
(define vEgoStand	4)
(define vEgoRun		5)
(define vEgoSneak	6)
(define vEgoSneakStand		8)
(define vBowToBaron			508)
(define vEgoThrowing		510)
(define vEgoCastFetch		520)
(define vEgoCastSpell		521)
(define vEgoCastDart		522)
(define vEgoThrowingDagger	524)
(define vEgoTrips			536)

;Ego fighting views
(define vKnFight		102)
(define vKnThrust		103)
(define vKnDodgeL		104)
(define vKnDodgeR		105)
(define vKnGetHit		106)
(define vFightSpell 	107)
(define vKnZap			108)
(define vSwFight		109)
(define vSwThrustLow	110)
(define vSwParryLow		111)
(define vSwDodgeR		112)
(define vSwGetHit		113)
(define vSwThrustHigh	114)
(define vSwParryHigh	115)
(define vSwDodgeL		116)
(define vEgoUnarmed		117)
(define vEgoTiredSword	514)		
(define vFightFX		535)

;All Fighting Characters
(define vBear 				420)
(define vBearDefeated 		421)
(define vBearFight 			422)
(define vBearHumanFight 	423)
(define vArenaDazzle		424)
(define vMinotaur			425)
(define vMinotaurDefeated	426)
(define vMinotaurFight 		427)
(define vSaurus 			430)
(define vSaurusDefeated 	431)
(define vSaurusFight 		432)
(define vMantray 			435)
(define vMantrayDefeated	436)
(define vMantrayFight 		437)
(define vCheetaur 			440)
(define vCheetaurDefeated 	441)
(define vCheetaurFight		442)
(define vCheetaurBite		443)
(define vCheetaurSlash		444)
(define vGoblin 			445)
(define vGoblinDefeated		446)
(define vGoblinFight		447)
(define vGoblinBush 		448)
(define vTroll 				450)
(define vTrollDefeated		451)
(define vTrollFight 		452)
(define vOgre 				455)
(define vOgreDefeated 		456)
(define vOgreFight 			457)
(define vDragon				460)	;although it's called a Saurus Rex in-game, it's
(define vDragonDefeated 	461)	; internally known as a dragon
(define vDragonFight 		462)
(define vBrigand 			465)
(define vBrigandDefeated	466)
(define vBrigandFight 		467)
(define vBrigandLeader		470)	;unused, but was likely the leader's arena
(define vBrigandLeaderFight 473)

(define vWeaponsMasterFight	638)
(define vWeaponsMaster		639)

(define vDeathIcons		800)
(define vCharSheet	802)
(define vStatusBar	803)
(define vMonoStatusBar 804)	;unused in VGA

;Intro graphics
(define pIntro			902)
(define vEndCredits		902)
(define pCredits	903)
(define pCharSel		905)
(define vIntroFlame			906)
(define vIntroFlame2		907)
(define vQFGCooldown		908)
(define vHeroCooldown		909)
(define vIntroDragon		910)
(define vIntroTitle			912)
(define vHalfSparkle		988)

;Character select graphics
(define vSelFighterSlow		206)
(define vSelMagicUserSlow	207)
(define vSelThiefSlow		208)
(define vCharSel			506)
(define vSelFighter			526)
(define vSelMagicUser		527)
(define vSelThief			528)

;Icon bar and cursor graphics
(define vRunCursor		937)
(define vPickUpCursor	938)
(define vDropCursor		939)
(define vWalkCursor		940)
(define vLookCursor		941)
(define vDoCursor		942)
(define vTalkCursor		943)
(define vSneakCursorAlt	944)	;unused
(define vCombatIcons	945)
(define vRunCursorAlt	946)	;unused
(define vSneakCursor	947)
(define vCastCursor		948)
(define vHelpCursor		949)
(define vInvItems		950)
(define vInvCursors		960)
(define vWindowBorders	989)	;unused
(define vIcons			990)
(define vInvIcons		991)
(define vSpellIcons		992)
(define vActionIcons	994)
(define vGameControls	995)

;Talker busts
(define vBarnardTalker		1014)
(define vKoboldTalker		1015)
(define vBabaTalker			1021)
(define vSkullTalker		1022)
(define vGargoyleTalker		1029)
(define vFenrusTalker		1031)
(define vErasmusTalker		1034)
(define vMeepTalker			1060)
(define vBaronTalker		1141)
(define vZaraTalker			1314)
(define vBarnard14Talker	1317)
(define vBartenderTalker	1331)

;Sound defines
(define sThemeSong		1)
(define sHardBattle		2)
(define sEasyBattle		3)
(define sEasyBattleEnd	7)
(define sGhosts			12)
(define sDazzle			17)
(define sCave			20)
(define sBabaHutOutside	23)
(define sEranasPeace	24)
(define sForest			25)
(define sDeath			26)
(define sTeleport		28)
(define sKnifeStick1	29)
(define sKnifeStick2	30)
(define sKnifeThrow		31)
(define sForestNight	32)
(define sFireDart		33)
(define sOpenLock		35)
(define sDeathGhost		37)
(define sHardBattleEnd	38)
(define sCalm			39)
(define sFireDartHits	45)
(define sWind			47)
(define sDeathBusted	52)
(define sMeepRock		58)
(define sCharSel		61)
(define sMagicShop		67)
(define sBrigand		73)
(define sTown			93)
(define sEndGame		99)
(define sHalfDome		100)
(define sEgoHurt		104)
(define sEgoDie			105)
(define sCheetaurRoar	107)
(define sSwoosh			109)
(define sShroomTrip		126)

;demo sounds
(define sTwinkle		992)
(define sUnsheathe		993)
(define sMoan1			994)
(define sMoan2			995)
(define sDemoFinale		996)
(define sRoar			997)
(define sShortBattle	998)
(define sShortIntro		999)