;;; Sierra Script
;;; Talkers.sh -- Produced by SCI Companion
;;; This file should only be edited with the SCI Companion message editor

;;; 

(define NARRATOR 99)
(define PRINTMSG 97)
(define SYSMSG 98)
(define WOLFGANG 1)
(define SHEMA 2)
(define SHAMEEN 3)
(define ABDULLA 4)
(define CHIEFTHIEF 5)
(define BORIS 6)
(define MEEP 7)
(define HILDE 8)
(define BARTENDER 9)
(define KARL 10)
(define BAKER 11)
(define BUTCHER 12)
(define CRUSHER 13)
(define BEGGAR 14)
(define SLINK 15)
(define ERASMUS 16)
(define FENRUS 17)
(define BARON 18)
(define BERNIE 19)
(define ZARA 20)
(define SHOPKEEPER 21)
(define GARGOYLE 23)
(define FOX 25)
(define BABA 26)
(define ELSA97 27)
(define STOOGE 28)
(define SKULL 29)
(define YORICK 30)
(define YORICK97 31)
(define BRAUGGI 32)
(define MASTER 33)
(define BRUNO 34)
(define BRUTUS 35)
(define HEINRICH 38)
(define HEALER 40)
(define BRUNO65 39)
(define SHERIFF 41)
(define DRYAD 42)
(define HERMIT 43)
(define STABLEMAN 45)
(define BERNIE171 46)
(define FAIRY1 47)
(define FAIRY2 48)
(define FAIRY3 49)
(define FAIRY4 50)
(define FAIRY5 51)

